version: '3.7'

services:
  dockerapiservice:
    image: dockerapi
    ports:
      - "8080:8080"
  
  dockerapitests:
    image: dockerapitests
    build:
      context: .
      dockerfile: DockerAPI.Tests/Dockerfile
    entrypoint: dotnet test
    depends_on:
      - dockerapiservice
  
networks:
    default:
        driver: bridge